# Generated by Django 5.1.4 on 2026-06-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=64)),
                ("external_id", models.CharField(max_length=128)),
                ("title", models.TextField()),
                ("text", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, max_length=1000)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("source", "external_id")},
            },
        ),
    ]
